---
title: "Instructors"
format: html
editor: visual
execute:
  message: false
  warning: false
  echo: false
  eval: false
---

```{r}
#| eval: true
library(readr)
library(dplyr)
library(tidyr)
library(reactable)
library(ggmap)
library(plotly)
```

```{r}
instructors <- read_delim("https://raw.githubusercontent.com/Bioconductor/bioconductor-teaching/master/bioc-instructors.md", delim = '|', trim_ws = TRUE) |> 
  filter(Name != "----------")
```

This is the table and map showing people in the Bioconductor community who are certified Carpentries instructors. If you are one and don't see your name, please add yourself as described in [this GitHub issue](https://github.com/Bioconductor/bioconductor-teaching/issues/22#issuecomment-1384258079).

```{r}
instructors_geocoded <- instructors |> 
  mutate_geocode(Location)
```


```{r}
#| eval: true
# need to find a way to automate this, currently have to get the locations locally using code above then hardcode them as below, as needs Google Maps API key to get the geocode info

instructors_geocoded <- tibble::tribble(
  ~...1,                ~Name,                ~Location,                   ~Institution,                                 ~www, ~...6,        ~lon,       ~lat,
     NA,      "Laurent Gatto",      "Brussels, Belgium",                    "UCLouvain",    "https://lgatto.github.io/about/",    NA,   4.3571696, 50.8476424,
     NA,  "Charlotte Soneson",     "Basel, Switzerland", "Friedrich Miescher Institute",        "https://csoneson.github.io/",    NA,   7.5885761, 47.5595986,
     NA, "Kevin Rue-Albrecht", "Oxford, United Kingdom",         "University of Oxford",        "https://kevinrue.github.io/",    NA,  -1.2577263, 51.7520209,
     NA,     "Robert Castelo",       "Barcelona, Spain",      "Pompeu Fabra University", "https://functionalgenomics.upf.edu",    NA,    2.168568, 41.3873974,
     NA,       "Kozo Nishida",           "Tokyo, Japan",              "Riken Institute",           "https://github.com/kozo2",    NA, 139.6503106, 35.6761919
  )
```

```{r}
#| eval: true
instructors_geocoded |> 
  select(Name, Institution, Location) |> 
  arrange(Name) |> 
  reactable()
```

```{r}
#| eval: true
world <- map_data("world")

gg <- ggplot() +
  geom_polygon(data = world, aes(x = long, y = lat, group = group), fill = "grey") +
  geom_jitter(data = instructors_geocoded, aes(x = lon, y = lat, text = paste(Name, Institution, sep = "\n")), color = 'red') +
  theme_void()

ggplotly(gg, tooltip = "text")
```
