---
title: "Workshops"
format: html
editor: visual
execute:
  message: false
  warning: false
  echo: false
---

```{r}
library(tidyr)
library(reactable)
library(ggmap)
library(plotly)
```

Workshops using the [Bioconductor Carpentries](https://www.bioconductor.org/help/education-training/) training material. See [this page](instructors.html) for Bioconductor Carpentries Instructors.

```{r}
# workshop info is not yet in md file, if it is could import from there
workshops <- tibble::tribble(
          ~Date,  ~`Hosted By`,  ~host_url, ~Workshop, ~workshop_url, ~Location,  ~Instructors,
    "March 2024", "University of Illinois",  "https://illinois.edu/", "bioc-intro", NA,  "Champaign", "Jenny Drnevich, Negin Valizadegan, Yifei Kang",
    "November 2023", NA, NA, "bioc-rnaseq", NA, "Belém", "Rodrigo Arcoverde Cerveira da Silva",
    "15 October 2023", "BioCAsia2023", "https://biocasia2023.bioconductor.org/", "bioc-rnaseq", NA, "Hong Kong", "David Shih",
    "12-13 October 2023", "Carnegie Institution", "https://bse.carnegiescience.edu", "bioc-rnaseq", NA, "Baltimore", "Javier Carpinteyro-Ponce, Frederick Tan",
    "9-12 October 2023", "University of Bergen", "https://www.uib.no/en", "bioc-intro", NA, "Bergen", "Leo Lahti",
    "October 2023", "University of Illinois",  "https://illinois.edu/", "bioc-intro", NA,  "Champaign", "Jenny Drnevich, Jessica Holmes, Yifei Kang",
    "18-19 September 2023",  "EuroBioC2023", "https://eurobioc2023.bioconductor.org/", "bioc-rnaseq", "https://bioconductor.github.io/2023-09-18-RNASeq-EuroBioc/", "Ghent", "Soneson Charlotte, Almut Lütge, Fabricio Almeida-Silva",
    "18-19 September 2023",  "EuroBioC2023", "https://eurobioc2023.bioconductor.org/", "bioc-intro", "https://bioconductor.github.io/2023-09-18-BiocIntro-EuroBioc/", "Ghent", "Laurent Gatto, Charlotte Hutchings, Olly Crook, Givanna Putri, Marcel Ramos Pérez",
    "31 July-1 August 2023",  "BioC2023",  "https://bioc2023.bioconductor.org/",  "bioc-intro", "https://bioconductor.github.io/2023-07-31-BiocRnaseq-Bioc2023/", "Boston",  "Jenny Drnevich, Sehyun Oh",
    "19-21 June 2023", "University of Oulu", "https://www.oulu.fi/en", "bioc-intro", NA, "Oulu", "Leo Lahti",
    "22-26 May 2023", "Galaxy Smörgåsbord 2023",  "https://gallantries.github.io/video-library/events/smorgasbord3/", "bioc-project", "https://gallantries.github.io/video-library/modules/bioconductor",  "online", "Kevin Rue-Albrecht",
    "22-26 May 2023", "Galaxy Smörgåsbord 2023",  "https://gallantries.github.io/video-library/events/smorgasbord3/", "bioc-intro", "https://gallantries.github.io/video-library/modules/bioconductor",  "online", "Laurent Gatto",
    "March 2023", "University of Illinois",  "https://illinois.edu/", "bioc-intro", NA,  "Champaign", "Jenny Drnevich, Jessica Holmes, Negin Valizadegan",
    "March 2023", "UCLouvain",  NA, "bioc-intro", NA,  "Brussels", "Laurent Gatto",
    "21-24 Feb 2023", "Savitribai Phule Pune University", "http://www.unipune.ac.in/", "bioc-intro", NA, "Pune", "Leo Lahti",
    "2023", NA,  NA, "bioc-intro", NA,  "Uzhhorod", "Laurent Gatto",
    "12-13 September 2022", "EuroBioC2022",  "https://eurobioc2022.bioconductor.org/", "bioc-intro", "https://bioconductor.github.io/2022-09-12-BiocIntro-Heidelberg/", "Heidelberg", "Charlotte Soneson, Laurent Gatto",
    "1, 8, 15, 22 June 2022", "Australian BioCommons", "https://www.biocommons.org.au/", "bioc-intro", "https://zenodo.org/records/6766951", "online", "Saskia Freytag, Adele Barugahare, Maria Doyle, Brendan Ansell",
    "2022", "UCLouvain",  NA, "bioc-intro", NA,  "Brussels", "Laurent Gatto"
  ) 
```


```{r}
# get coordinates to map
workshops_geocoded <- workshops |> 
  mutate_geocode(Location)
```

```{r}
world_map <- map_data("world")
world_map <- subset(world_map, region != "Antarctica")

gg <- ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill = "grey") +
  geom_jitter(data = workshops_geocoded, aes(x = lon, y = lat, text = paste(`Hosted By`, Location, sep = "\n")), color = 'red') +
  theme_void()

ggplotly(gg, tooltip = "text")
```

```{r}
workshops_geocoded |> 
  select(-lon, -lat, -host_url, -workshop_url) |>
  reactable(columns = list(
   `Hosted By` = colDef(cell = function(value, index) {
      # Render as a link
      htmltools::tags$a(href = workshops_geocoded$host_url[index], target = "_blank", as.character(value))
      }),
    Workshop = colDef(cell = function(value, index) {
      # Render as a link
      htmltools::tags$a(href = workshops_geocoded$workshop_url[index], target = "_blank", as.character(value))
      })
    ), 
    defaultPageSize = 100)
```
